apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrtest-velero-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mrtest-velero-operator
  template:
    metadata:
      labels:
        name: mrtest-velero-operator
    spec:
      serviceAccountName: mrtest-velero-operator
      containers:
        - name: mrtest-velero-operator
          # Replace this with the built image name
          image: docker pull quay.io/manrajag/mrtest-velero-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mrtest-velero-operator"
